### ISSUE TITLE
Unable to create new Client

### ISSUE THREAD

**Issue by hthetiot** [TelegramPassport/passport-js#1]
Using https://telepass.me I'm unable to create Client to get clientID and clientSecret due form not working. 

<img width="646" alt="screen shot 2016-11-06 at 7 36 38 pm" src="https://cloud.githubusercontent.com/assets/8635/20045705/8c5c0af0-a458-11e6-9f49-d5445d548512.png">

**Comment by ingria** [comment]
@hthetiot, fixed! Thanks for the report.

**Comment by hthetiot** [comment]
@ingria Fix confirmed. Thx.
