### ISSUE TITLE
Telegram bot does not reply to auth requests

### ISSUE THREAD

**Issue by timelf123** [TelegramPassport/passport-js#3]
after doing `/start CODEHERE` I am not logged in and the bot does not reply. Have waited 24 hours now

**Comment by timelf123** [comment]
It finally replied, 12 hours later

**Comment by ingria** [comment]
This project is temporary closed and not supported because Telegram [has launched](https://core.telegram.org/widgets/login) its own native auth platform.

Thanks for the report anyway 👍
